Make investor pane placement make more sense
FreeAllegiance/Artwork pull request #6
Opened 2017-10-03 15:00 UTC by Xynth22

Change from Bunnywabbit to make investor pane placement make more sense

2017-10-03 15:02 UTC, Xynth22 commented
@hheimbuerger Cort, can you double check this. Link to forum discussion, I am merely the messenger.

https://www.freeallegiance.org/forums/index.php?showtopic=72367

@BackTrak

2017-10-05 13:33 UTC, hheimbuerger requested changes
Besides my change requests on individual lines, I think this is a great idea and should be merged!

2017-10-05 13:33 UTC, hheimbuerger commented on dialog.mdl
> +        //Change from Bunnywabbit to make investor pane placement make more sense
@Xynth22 I'm in favor of no longer having historical information stored in the code. That's what git is great for.

Let's remove lines 5375 and 5376.

2017-10-05 13:33 UTC, hheimbuerger commented on dialog.mdl
> +        (MergedInvestmentsPaneImage, SideRight, Point(10, -265), Point(-490, -265), .2, ofInvestment, false),
I think we should keep the animations consistent. I find it subconsciously confusing if every window has a different animation (length, positioning, etc.). Therefore, I suggest we keep this animation at `.5`s.

2017-10-05 15:25 UTC, Xynth22 commented
incorporated Cort's comments. Ready to go!

2017-10-05 18:27 UTC, hheimbuerger requested changes

2017-10-05 18:27 UTC, hheimbuerger commented on dialog.mdl
> +        //(MergedInvestmentsPaneImage, SideCenter, Point(-192, 2000), Point(-192, -265), .5, ofInvestment, false),
No need to keep this line either! Also, it's literally the same as the one below now! :)

2017-10-05 22:01 UTC, Xynth22 commented
Ah that does look better in Git when you do it that way.

2017-10-06 07:23 UTC, hheimbuerger approved these changes

2017-10-06 07:23 UTC, hheimbuerger commented on dialog.mdl
> +        // MergedInvestmentsPaneImage: the investments pane (F5)
You added a whole bunch of spaces at the end of this line. :)

2017-10-06 15:48 UTC, Xynth22 commented
Done.

2017-10-12 02:54 UTC, merged

2017-10-12 02:54 UTC, BackTrak commented
sorry guys, totally missed that there were pulls waiting in artwork!